### ISSUE TITLE
Temporary (libbi) files are not cleaned up when going out of scope

### ISSUE THREAD

**Issue by BlackEdder** [libbi/RBi#10]
Currently temporary files under `/tmp` are kept around even after they go out of scope. Because these files are quite large this leads to the disk slowly filling up on my laptop when I run multiple analyses from the same R session.

**Comment by sbfnk** [comment]
I'm not aware of a way to track variables going out of scope because `R` only deals with them at the moment of garbage collection, but you install the latest head version (https://github.com/libbi/RBi/commit/9e5b21e51441e2a98c979286567d766864059381) a call to `gc()` should remove the temporary files for all `libbi` objects that don't exist any longer.

**Comment by sbfnk** [comment]
I'm closing this as solved.

**Comment by BlackEdder** [comment]
Thanks! I tested the gc() method and that solved the problem for me.
